.IGNORE:

HANDLE := $(shell git config --get remote.origin.url)

all:
	echo $(HANDLE)

cfg:
	git config --global user.email "andy.e.ritz@gmail.com"
	git config --global user.name "Andrew Ritz"
	git config --global core.editor "vi"

push:
	git push -u origin master
	
status:
	git status

update: 
	git add . --all
	git commit -a
	git push

refresh:
	rm -rf .git
	git init
	git add .
	git commit -m "removed history"
	git remote add origin $(HANDLE) 
	git push -u --force origin master

helper:
	git config --global credential.helper store

helperw:
	git config --global credential.helper wincred

